# Generated by Django 3.1.6 on 2021-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(default='', upload_to='images/expenses'),
        ),
    ]
