# Generated by Django 3.1.6 on 2021-03-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20210320_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='income',
            name='image',
            field=models.ImageField(default='', upload_to='images/incomes'),
        ),
    ]
