# Generated by Django 3.1.6 on 2021-03-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20210320_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, default='images/expenses/default.jpg', upload_to='images/expenses'),
        ),
    ]
