# Generated by Django 3.1.6 on 2021-03-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20210320_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='image',
            field=models.ImageField(blank=True, default='images/expenses/default.jpg', upload_to='images/incomes'),
        ),
    ]
