# Generated by Django 3.1.6 on 2021-03-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20210320_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/expenses'),
        ),
    ]
